[package]
name = "HPOHandler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastobo = "0.15.1"
ureq = "2.6.2"
